### ISSUE TITLE
Suggested Rewrite of Bad things happen to good science. 

### ISSUE THREAD

**Issue by kstocks** [trustedci/OSCRP#19]
I suggest rewriting the section "Bad things happen to good science" as follows, to streamline it:

> There are numerous examples of open science projects being affected by attacks over computer networks. Some of these attacks have specifically targeted the science projects, while in other examples, science projects have simply been collateral damage. Several real examples, with identifying details removed, are described below. They show that the damage can range
> from simple disruption and some loss of work time to vast amounts of money spent to attempt to repair systems and recover scientific data, significant impact on those projects being able to fulfill their mission. 
> Consequences of malicious tampering have historically been organized into three categories: integrity, availability, and confidentiality. With respect to integrity, it is critical that scientific outputs be trusted as uncorrupted if they are to be used as the foundation for future science and critical policy decisions. The loss of availability of valuable data or instruments can slow the scientific process, lead to lost science opportunities (e.g. if data are permanently lost, or a sensor is down during a particular natural phenomenon), be expensive to replace, and lead to embarrassment and a loss of reputation. And finally, even open science projects generally have confidentiality concerns with respect to embargoed data, such as data that have not been quality assessed or will be released after publication, and restricted data, such as personally identifiable information that Federal regulations prohibit exposing. 

And then move this last paragraph (below) to _after_ the list security incidents (right above how to use this doc), to act as a summary and segue:

> The point we emphasize with these examples is that computer security-related consequences in open science can be as important as consequences elsewhere, and researchers should not assume that simply because data are eventually intended to be published openly that they should not care about computer security. Nor should researchers assume that their institutions will protect them—at least not without active engagement between the PI and the institution.

**Comment by thanne23** [comment]
I think both of these suggestions (the streamlined wording and moving that paragraph) look really good.  One small suggested change to the streamlined wording section, for readability:
Instead of:

They show that the damage can range from simple disruption and some loss of work time to vast amounts of money spent to attempt to repair systems and recover scientific data, significant impact on those projects being able to fulfill their mission. 

How about:

They show that the damage can range from simple disruption and some loss of work time to vast amounts of money spent to repair systems and recover scientific data, with significant impact on those projects being able to fulfill their mission.

**Comment by kstocks** [comment]
Bad Things section rewritten, and final paragraph moved, as per proposal, with RuthAnne and Dop's (by email) tweaks included.
